const content = d3.select("#content")

content.append("br")
content.append("br")
content.append("h1").text("Hi!")
content.append("p").text("I'm ")
       .append("a").text("Amelia Wattenberger").attr("href", "http://wattenberger.com/")
content.append("p").text("Follow along and get your hands dirty! Download this code from")
content.append("a").text("github.com/Wattenberger/d3-examples").attr("href", "https://github.com/Wattenberger/d3-examples")
content.append("div").text("or")
content.append("a").text("is.gd/rocd3").attr("href", "https://is.gd/rocd3")


let section = content.append("div").attr("class", "section")
section.append("h2").text("The Plan")
let list = section.append("ol")
list.append("li").text("What is d3.js?")
list.append("li").text("Drawing with d3.js")
list.append("li").text("Looking at some Rochester data")
list.append("li").text("Making a scale")
list.append("li").text("Making a line graph")
list.append("li").text("How d3.js joins data with elements")
list.append("li").text("Making a scatterplot")
list.append("li").text("Is this April colder than normal?")
list.append("li").text("???")
list.append("li").text("Profit")
